// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuditHandler 审计日志处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearLogs 清空日志
 */
export function ClearLogs(): $CancellablePromise<void> {
    return $Call.ByID(368239150);
}

/**
 * ExportLogs 导出日志
 */
export function ExportLogs(req: $models.ExportLogsRequest | null): $CancellablePromise<void> {
    return $Call.ByID(3729356493, req);
}

/**
 * GetLogs 获取日志列表
 */
export function GetLogs(req: $models.GetLogsRequest | null): $CancellablePromise<$models.GetLogsResponse | null> {
    return $Call.ByID(1174997751, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLogsByUser 按用户获取日志
 */
export function GetLogsByUser(req: $models.GetLogsByUserRequest | null): $CancellablePromise<$models.GetLogsResponse | null> {
    return $Call.ByID(1680128037, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStatistics 获取统计信息
 */
export function GetStatistics(): $CancellablePromise<$models.GetStatisticsResponse | null> {
    return $Call.ByID(4202376111).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Log 记录审计日志
 */
export function Log(req: $models.LogRequest | null): $CancellablePromise<void> {
    return $Call.ByID(1141844482, req);
}

/**
 * SearchLogs 搜索日志
 */
export function SearchLogs(req: $models.SearchLogsRequest | null): $CancellablePromise<$models.GetLogsResponse | null> {
    return $Call.ByID(1004858199, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GetLogsResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GetStatisticsResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
