// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchHandler 批量操作处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchDelete 批量删除
 */
export function BatchDelete(req: $models.BatchDeleteRequest | null): $CancellablePromise<$models.BatchOperationResponse | null> {
    return $Call.ByID(2503342154, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BatchTest 批量测试连接
 */
export function BatchTest(req: $models.BatchTestRequest | null): $CancellablePromise<$models.BatchOperationResponse | null> {
    return $Call.ByID(220726757, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * BatchUpdateStatus 批量更新状态
 */
export function BatchUpdateStatus(req: $models.BatchUpdateStatusRequest | null): $CancellablePromise<$models.BatchOperationResponse | null> {
    return $Call.ByID(853598974, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Export 批量导出
 */
export function Export(req: $models.ExportRequest | null): $CancellablePromise<$models.ExportResponse | null> {
    return $Call.ByID(3800984841, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetImportTemplate 获取导入模板
 */
export function GetImportTemplate(req: $models.GetImportTemplateRequest | null): $CancellablePromise<$models.GetImportTemplateResponse | null> {
    return $Call.ByID(880401126, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Import 批量导入
 */
export function Import(req: $models.ImportRequest | null): $CancellablePromise<$models.BatchOperationResponse | null> {
    return $Call.ByID(4238099690, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ValidateImport 验证导入数据
 */
export function ValidateImport(req: $models.ValidateImportRequest | null): $CancellablePromise<$models.BatchOperationResponse | null> {
    return $Call.ByID(267441548, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BatchOperationResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ExportResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GetImportTemplateResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
