// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandHandler 命令执行处理器（Wails 绑定用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExecuteCommand 执行命令
 * @summary 执行命令
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param command 要执行的命令
 * @param timeout 超时时间（秒）
 * @return 命令执行结果
 */
export function ExecuteCommand(webshellID: string, command: string, timeout: number): $CancellablePromise<$models.CommandResult | null> {
    return $Call.ByID(2651446334, webshellID, command, timeout).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteCommandWithResult 执行命令并返回结构化结果
 * @summary 执行命令并返回结构化结果
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param command 要执行的命令
 * @return 结构化结果
 */
export function ExecuteCommandWithResult(webshellID: string, command: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(2906348451, webshellID, command).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetCurrentUser 获取当前用户
 * @summary 获取当前用户
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @return 用户名
 */
export function GetCurrentUser(webshellID: string): $CancellablePromise<string> {
    return $Call.ByID(992311620, webshellID);
}

/**
 * GetSystemInfo 获取系统信息
 * @summary 获取系统信息
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @return 系统信息
 */
export function GetSystemInfo(webshellID: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1949406955, webshellID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetWorkingDirectory 获取工作目录
 * @summary 获取工作目录
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @return 工作目录路径
 */
export function GetWorkingDirectory(webshellID: string): $CancellablePromise<string> {
    return $Call.ByID(2318944952, webshellID);
}

/**
 * KillProcess 终止进程
 * @summary 终止进程
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param pid 进程 ID
 * @return 错误信息
 */
export function KillProcess(webshellID: string, pid: number): $CancellablePromise<void> {
    return $Call.ByID(44318331, webshellID, pid);
}

// Private type creation functions
const $$createType0 = $models.CommandResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
