// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionHandler 连接管理处理器（Wails 绑定用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../domain/entity/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect 连接 WebShell
 * @summary 连接到 WebShell
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param url 目标 URL
 * @param password 密码
 * @param encoder 编码器类型（none/base64/rot13/xor）
 * @param encryptionKey 加密密钥
 * @param timeout 超时时间（秒）
 * @param proxyType 代理类型（none/http/https/socks5）
 * @param proxyAddress 代理地址
 * @param sslVerify 是否验证 SSL
 * @return 连接结果
 */
export function Connect(webshellID: string, url: string, password: string, encoder: string, encryptionKey: string, timeout: number, proxyType: string, proxyAddress: string, sslVerify: boolean): $CancellablePromise<$models.ConnectResult | null> {
    return $Call.ByID(3921075097, webshellID, url, password, encoder, encryptionKey, timeout, proxyType, proxyAddress, sslVerify).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Disconnect 断开 WebShell 连接
 * @summary 断开 WebShell 连接
 * @param webshellID WebShell ID
 * @return 错误信息
 */
export function Disconnect(webshellID: string): $CancellablePromise<void> {
    return $Call.ByID(1852533259, webshellID);
}

/**
 * GetAllConnections 获取所有连接
 * @summary 获取所有连接
 * @return 连接列表
 */
export function GetAllConnections(): $CancellablePromise<(entity$0.Connection | null)[]> {
    return $Call.ByID(1888455167).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetConnection 获取连接状态
 * @summary 获取连接状态
 * @param webshellID WebShell ID
 * @return 连接信息
 */
export function GetConnection(webshellID: string): $CancellablePromise<entity$0.Connection | null> {
    return $Call.ByID(3093586159, webshellID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetConnectionCount 获取连接数量
 * @summary 获取连接数量
 * @return 连接数量
 */
export function GetConnectionCount(): $CancellablePromise<number> {
    return $Call.ByID(3944447158);
}

// Private type creation functions
const $$createType0 = $models.ConnectResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = entity$0.Connection.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
