// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseHandler 数据库管理处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect 连接数据库
 */
export function Connect(req: $models.ConnectRequest | null): $CancellablePromise<$models.ConnectResponse | null> {
    return $Call.ByID(1027044738, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Disconnect 断开数据库连接
 */
export function Disconnect(req: $models.DisconnectRequest | null): $CancellablePromise<$models.ConnectResponse | null> {
    return $Call.ByID(940401606, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteQuery 执行 SQL 查询
 */
export function ExecuteQuery(req: $models.ExecuteQueryRequest | null): $CancellablePromise<$models.ExecuteQueryResponse | null> {
    return $Call.ByID(1343710105, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ExecuteUpdate 执行 SQL 更新
 */
export function ExecuteUpdate(req: $models.ExecuteUpdateRequest | null): $CancellablePromise<$models.ExecuteQueryResponse | null> {
    return $Call.ByID(2361409802, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetDatabases 获取数据库列表（用于 MySQL/PostgreSQL）
 */
export function GetDatabases(req: $models.GetDatabasesRequest | null): $CancellablePromise<$models.GetDatabasesResponse | null> {
    return $Call.ByID(943142978, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTableColumns 获取表列信息
 */
export function GetTableColumns(req: $models.GetTableColumnsRequest | null): $CancellablePromise<$models.GetTableColumnsResponse | null> {
    return $Call.ByID(2008472839, req).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetTables 获取数据库表列表
 */
export function GetTables(req: $models.GetTablesRequest | null): $CancellablePromise<$models.GetTablesResponse | null> {
    return $Call.ByID(2627242877, req).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * TestConnection 测试数据库连接
 */
export function TestConnection(req: $models.TestConnectionRequest | null): $CancellablePromise<$models.TestConnectionResponse | null> {
    return $Call.ByID(1167140096, req).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ConnectResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ExecuteQueryResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GetDatabasesResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.GetTableColumnsResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.GetTablesResponse.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.TestConnectionResponse.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
