// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EncryptionHandler 加密处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DecryptRequest 解密数据
 */
export function DecryptRequest(req: $models.DecryptRequestRequest | null): $CancellablePromise<$models.DecryptRequestResponse | null> {
    return $Call.ByID(770870258, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * EncryptRequest 加密数据
 */
export function EncryptRequest(req: $models.EncryptRequestRequest | null): $CancellablePromise<$models.EncryptRequestResponse | null> {
    return $Call.ByID(3942517418, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GenerateConfig 生成加密配置
 */
export function GenerateConfig(req: $models.GenerateConfigRequest | null): $CancellablePromise<$models.GenerateConfigResponse | null> {
    return $Call.ByID(1569289057, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * InitEncryption 初始化加密服务
 */
export function InitEncryption(config: $models.EncryptionConfig | null): $CancellablePromise<$models.EncryptionResponse | null> {
    return $Call.ByID(2564103627, config).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * TestEncryption 测试加密解密
 */
export function TestEncryption(req: $models.TestEncryptionRequest | null): $CancellablePromise<$models.TestEncryptionResponse | null> {
    return $Call.ByID(176528441, req).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ValidateConfig 验证加密配置
 */
export function ValidateConfig(req: $models.ValidateConfigRequest | null): $CancellablePromise<$models.ValidateConfigResponse | null> {
    return $Call.ByID(2537082380, req).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DecryptRequestResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.EncryptRequestResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.GenerateConfigResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.EncryptionResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.TestEncryptionResponse.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.ValidateConfigResponse.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
