// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileHandler 文件管理处理器（Wails 绑定用）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../services/models.js";

/**
 * CreateDirectory 创建目录
 * @summary 创建目录
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 目录路径
 * @return 错误信息
 */
export function CreateDirectory(webshellID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(406144354, webshellID, path);
}

/**
 * DeleteFile 删除文件
 * @summary 删除文件
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 文件路径
 * @return 错误信息
 */
export function DeleteFile(webshellID: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(4277054470, webshellID, path);
}

/**
 * DownloadFile 下载文件
 * @summary 下载文件
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 文件路径
 * @return 文件内容（字节）
 */
export function DownloadFile(webshellID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(847802841, webshellID, path).then(($result: any) => {
        return $Create.ByteSlice($result);
    });
}

/**
 * GetDiskUsage 获取磁盘使用情况
 * @summary 获取磁盘使用情况
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @return 磁盘使用信息
 */
export function GetDiskUsage(webshellID: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3201148595, webshellID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFilePermissions 获取文件权限
 * @summary 获取文件权限
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 文件路径
 * @return 权限字符串
 */
export function GetFilePermissions(webshellID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(4112544525, webshellID, path);
}

/**
 * ListFiles 列出目录内容
 * @summary 列出目录内容
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 目录路径
 * @return 文件列表
 */
export function ListFiles(webshellID: string, path: string): $CancellablePromise<services$0.FileListResponse | null> {
    return $Call.ByID(2396256530, webshellID, path).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ReadFile 读取文件
 * @summary 读取文件内容
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 文件路径
 * @param limit 读取限制（字节）
 * @return 文件内容
 */
export function ReadFile(webshellID: string, path: string, limit: number): $CancellablePromise<string> {
    return $Call.ByID(904234937, webshellID, path, limit);
}

/**
 * RenameFile 重命名文件
 * @summary 重命名文件/目录
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param oldPath 原路径
 * @param newPath 新路径
 * @return 错误信息
 */
export function RenameFile(webshellID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(2628339407, webshellID, oldPath, newPath);
}

/**
 * SearchFiles 搜索文件
 * @summary 搜索文件
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 搜索路径
 * @param pattern 搜索模式
 * @return 文件列表
 */
export function SearchFiles(webshellID: string, path: string, pattern: string): $CancellablePromise<services$0.FileInfo[]> {
    return $Call.ByID(955525762, webshellID, path, pattern).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * SetFilePermissions 设置文件权限
 * @summary 设置文件权限
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 文件路径
 * @param permissions 权限（如 755）
 * @return 错误信息
 */
export function SetFilePermissions(webshellID: string, path: string, permissions: string): $CancellablePromise<void> {
    return $Call.ByID(270091617, webshellID, path, permissions);
}

/**
 * UploadFile 上传文件
 * @summary 上传文件
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 上传路径
 * @param filename 文件名
 * @param content 文件内容（Base64）
 * @return 错误信息
 */
export function UploadFile(webshellID: string, path: string, filename: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2025617824, webshellID, path, filename, content);
}

/**
 * WriteFile 写入文件
 * @summary 写入文件内容
 * @param ctx 上下文
 * @param webshellID WebShell ID
 * @param path 文件路径
 * @param content 文件内容
 * @param isBase64 是否为 Base64 编码
 * @return 错误信息
 */
export function WriteFile(webshellID: string, path: string, content: string, isBase64: boolean): $CancellablePromise<void> {
    return $Call.ByID(3511561568, webshellID, path, content, isBase64);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = services$0.FileListResponse.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = services$0.FileInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
