// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../domain/entity/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plugin$0 from "../../plugin/models.js";

/**
 * AddCustomTemplateRequest 添加模板请求
 */
export class AddCustomTemplateRequest {
    "name": string;
    "type": string;
    "function": string;
    "content": string;

    /** Creates a new AddCustomTemplateRequest instance. */
    constructor($$source: Partial<AddCustomTemplateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            this["function"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddCustomTemplateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddCustomTemplateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddCustomTemplateRequest($$parsedSource as Partial<AddCustomTemplateRequest>);
    }
}

/**
 * BatchDeleteRequest 批量删除请求
 */
export class BatchDeleteRequest {
    "ids": string[];

    /** Creates a new BatchDeleteRequest instance. */
    constructor($$source: Partial<BatchDeleteRequest> = {}) {
        if (!("ids" in $$source)) {
            this["ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchDeleteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchDeleteRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField0_0($$parsedSource["ids"]);
        }
        return new BatchDeleteRequest($$parsedSource as Partial<BatchDeleteRequest>);
    }
}

/**
 * BatchOperationResponse 批量操作响应
 */
export class BatchOperationResponse {
    "total": number;
    "success": number;
    "failed": number;
    "errors": string[];
    "skipped": number;
    "duration": string;

    /** Creates a new BatchOperationResponse instance. */
    constructor($$source: Partial<BatchOperationResponse> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = 0;
        }
        if (!("failed" in $$source)) {
            this["failed"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchOperationResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchOperationResponse {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new BatchOperationResponse($$parsedSource as Partial<BatchOperationResponse>);
    }
}

/**
 * BatchTestRequest 批量测试请求
 */
export class BatchTestRequest {
    "ids": string[];

    /** Creates a new BatchTestRequest instance. */
    constructor($$source: Partial<BatchTestRequest> = {}) {
        if (!("ids" in $$source)) {
            this["ids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchTestRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchTestRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField0_0($$parsedSource["ids"]);
        }
        return new BatchTestRequest($$parsedSource as Partial<BatchTestRequest>);
    }
}

/**
 * BatchUpdateStatusRequest 批量更新状态请求
 */
export class BatchUpdateStatusRequest {
    "ids": string[];
    "status": string;

    /** Creates a new BatchUpdateStatusRequest instance. */
    constructor($$source: Partial<BatchUpdateStatusRequest> = {}) {
        if (!("ids" in $$source)) {
            this["ids"] = [];
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchUpdateStatusRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchUpdateStatusRequest {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField0_0($$parsedSource["ids"]);
        }
        return new BatchUpdateStatusRequest($$parsedSource as Partial<BatchUpdateStatusRequest>);
    }
}

/**
 * CloseWebShellWindowRequest 关闭 WebShell 窗口请求
 */
export class CloseWebShellWindowRequest {
    "webshell_id": string;

    /** Creates a new CloseWebShellWindowRequest instance. */
    constructor($$source: Partial<CloseWebShellWindowRequest> = {}) {
        if (!("webshell_id" in $$source)) {
            this["webshell_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CloseWebShellWindowRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CloseWebShellWindowRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CloseWebShellWindowRequest($$parsedSource as Partial<CloseWebShellWindowRequest>);
    }
}

/**
 * CommandResult 命令执行结果
 */
export class CommandResult {
    "output": string;
    "error": string;
    "exit_code": number;
    "duration": number;
    "success": boolean;

    /** Creates a new CommandResult instance. */
    constructor($$source: Partial<CommandResult> = {}) {
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("exit_code" in $$source)) {
            this["exit_code"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandResult($$parsedSource as Partial<CommandResult>);
    }
}

/**
 * ConnectRequest 连接请求
 */
export class ConnectRequest {
    "id": number;
    "name": string;
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;
    "charset": string;
    "ssl_mode": boolean;

    /** Creates a new ConnectRequest instance. */
    constructor($$source: Partial<ConnectRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("charset" in $$source)) {
            this["charset"] = "";
        }
        if (!("ssl_mode" in $$source)) {
            this["ssl_mode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectRequest($$parsedSource as Partial<ConnectRequest>);
    }
}

/**
 * ConnectResponse 连接响应
 */
export class ConnectResponse {
    "success": boolean;
    "message": string;

    /** Creates a new ConnectResponse instance. */
    constructor($$source: Partial<ConnectResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectResponse($$parsedSource as Partial<ConnectResponse>);
    }
}

/**
 * ConnectResult 连接结果
 */
export class ConnectResult {
    "success": boolean;
    "message": string;
    "connection": entity$0.Connection | null;

    /** Creates a new ConnectResult instance. */
    constructor($$source: Partial<ConnectResult> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("connection" in $$source)) {
            this["connection"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectResult {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("connection" in $$parsedSource) {
            $$parsedSource["connection"] = $$createField2_0($$parsedSource["connection"]);
        }
        return new ConnectResult($$parsedSource as Partial<ConnectResult>);
    }
}

/**
 * DecryptRequestRequest 解密请求请求
 */
export class DecryptRequestRequest {
    /**
     * EncryptedData 加密数据
     */
    "encrypted_data": string;

    /**
     * Timestamp 时间戳
     */
    "timestamp": number;

    /**
     * Signature 签名
     */
    "signature": string;

    /**
     * Window 时间窗口（秒）
     */
    "window": number;

    /** Creates a new DecryptRequestRequest instance. */
    constructor($$source: Partial<DecryptRequestRequest> = {}) {
        if (!("encrypted_data" in $$source)) {
            this["encrypted_data"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }
        if (!("window" in $$source)) {
            this["window"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecryptRequestRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DecryptRequestRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DecryptRequestRequest($$parsedSource as Partial<DecryptRequestRequest>);
    }
}

/**
 * DecryptRequestResponse 解密请求响应
 */
export class DecryptRequestResponse {
    /**
     * Data 解密后的数据
     */
    "data": string;

    /**
     * Valid 是否有效
     */
    "valid": boolean;

    /**
     * Message 消息
     */
    "message": string;

    /** Creates a new DecryptRequestResponse instance. */
    constructor($$source: Partial<DecryptRequestResponse> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DecryptRequestResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DecryptRequestResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DecryptRequestResponse($$parsedSource as Partial<DecryptRequestResponse>);
    }
}

/**
 * DisablePluginRequest 禁用插件请求
 */
export class DisablePluginRequest {
    "plugin_id": string;

    /** Creates a new DisablePluginRequest instance. */
    constructor($$source: Partial<DisablePluginRequest> = {}) {
        if (!("plugin_id" in $$source)) {
            this["plugin_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisablePluginRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DisablePluginRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisablePluginRequest($$parsedSource as Partial<DisablePluginRequest>);
    }
}

/**
 * DisablePluginResponse 禁用插件响应
 */
export class DisablePluginResponse {
    "success": boolean;
    "message": string;

    /** Creates a new DisablePluginResponse instance. */
    constructor($$source: Partial<DisablePluginResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisablePluginResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): DisablePluginResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisablePluginResponse($$parsedSource as Partial<DisablePluginResponse>);
    }
}

/**
 * DisconnectRequest 断开连接请求
 */
export class DisconnectRequest {
    "conn_id": number;

    /** Creates a new DisconnectRequest instance. */
    constructor($$source: Partial<DisconnectRequest> = {}) {
        if (!("conn_id" in $$source)) {
            this["conn_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisconnectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): DisconnectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DisconnectRequest($$parsedSource as Partial<DisconnectRequest>);
    }
}

/**
 * EnablePluginRequest 启用插件请求
 */
export class EnablePluginRequest {
    "plugin_id": string;

    /** Creates a new EnablePluginRequest instance. */
    constructor($$source: Partial<EnablePluginRequest> = {}) {
        if (!("plugin_id" in $$source)) {
            this["plugin_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnablePluginRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnablePluginRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnablePluginRequest($$parsedSource as Partial<EnablePluginRequest>);
    }
}

/**
 * EnablePluginResponse 启用插件响应
 */
export class EnablePluginResponse {
    "success": boolean;
    "message": string;

    /** Creates a new EnablePluginResponse instance. */
    constructor($$source: Partial<EnablePluginResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnablePluginResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): EnablePluginResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnablePluginResponse($$parsedSource as Partial<EnablePluginResponse>);
    }
}

/**
 * EncryptRequestRequest 加密请求请求
 */
export class EncryptRequestRequest {
    /**
     * Data 要加密的数据（Base64）
     */
    "data": string;

    /** Creates a new EncryptRequestRequest instance. */
    constructor($$source: Partial<EncryptRequestRequest> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptRequestRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EncryptRequestRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncryptRequestRequest($$parsedSource as Partial<EncryptRequestRequest>);
    }
}

/**
 * EncryptRequestResponse 加密请求响应
 */
export class EncryptRequestResponse {
    /**
     * EncryptedData 加密后的数据
     */
    "encrypted_data": string;

    /**
     * Timestamp 时间戳
     */
    "timestamp": number;

    /**
     * Signature 签名
     */
    "signature": string;

    /** Creates a new EncryptRequestResponse instance. */
    constructor($$source: Partial<EncryptRequestResponse> = {}) {
        if (!("encrypted_data" in $$source)) {
            this["encrypted_data"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptRequestResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): EncryptRequestResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncryptRequestResponse($$parsedSource as Partial<EncryptRequestResponse>);
    }
}

/**
 * EncryptionConfig 加密配置请求
 */
export class EncryptionConfig {
    /**
     * Key 加密密钥（16 进制）
     */
    "key": string;

    /**
     * IV 初始化向量（16 进制）
     */
    "iv": string;

    /**
     * Signature 签名密钥（16 进制）
     */
    "signature": string;

    /** Creates a new EncryptionConfig instance. */
    constructor($$source: Partial<EncryptionConfig> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("iv" in $$source)) {
            this["iv"] = "";
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): EncryptionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncryptionConfig($$parsedSource as Partial<EncryptionConfig>);
    }
}

/**
 * EncryptionResponse 加密操作响应
 */
export class EncryptionResponse {
    "success": boolean;
    "message": string;

    /** Creates a new EncryptionResponse instance. */
    constructor($$source: Partial<EncryptionResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EncryptionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): EncryptionResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EncryptionResponse($$parsedSource as Partial<EncryptionResponse>);
    }
}

/**
 * ExecuteQueryRequest 执行查询请求
 */
export class ExecuteQueryRequest {
    "conn_id": number;
    "sql": string;
    "limit": number;
    "offset": number;
    "timeout": number;

    /** Creates a new ExecuteQueryRequest instance. */
    constructor($$source: Partial<ExecuteQueryRequest> = {}) {
        if (!("conn_id" in $$source)) {
            this["conn_id"] = 0;
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteQueryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteQueryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecuteQueryRequest($$parsedSource as Partial<ExecuteQueryRequest>);
    }
}

/**
 * ExecuteQueryResponse 执行查询响应
 */
export class ExecuteQueryResponse {
    "columns": string[];
    "rows": { [_ in string]?: any }[];
    "affected": number;
    "duration": string;
    "success": boolean;
    "message": string;

    /** Creates a new ExecuteQueryResponse instance. */
    constructor($$source: Partial<ExecuteQueryResponse> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("affected" in $$source)) {
            this["affected"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteQueryResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteQueryResponse {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new ExecuteQueryResponse($$parsedSource as Partial<ExecuteQueryResponse>);
    }
}

/**
 * ExecuteUpdateRequest 执行更新请求
 */
export class ExecuteUpdateRequest {
    "conn_id": number;
    "sql": string;

    /** Creates a new ExecuteUpdateRequest instance. */
    constructor($$source: Partial<ExecuteUpdateRequest> = {}) {
        if (!("conn_id" in $$source)) {
            this["conn_id"] = 0;
        }
        if (!("sql" in $$source)) {
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecuteUpdateRequest($$parsedSource as Partial<ExecuteUpdateRequest>);
    }
}

/**
 * ExportLogsRequest 导出日志请求
 */
export class ExportLogsRequest {
    "file_path": string;

    /** Creates a new ExportLogsRequest instance. */
    constructor($$source: Partial<ExportLogsRequest> = {}) {
        if (!("file_path" in $$source)) {
            this["file_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportLogsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportLogsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportLogsRequest($$parsedSource as Partial<ExportLogsRequest>);
    }
}

/**
 * ExportRequest 导出请求
 */
export class ExportRequest {
    /**
     * IDs 导出的 ID 列表
     */
    "ids": number[];

    /**
     * Format 导出格式（json/csv/xml）
     */
    "format": string;

    /**
     * Filename 输出文件名
     */
    "filename": string;

    /**
     * FileType 文件类型
     */
    "file_type": string;

    /** Creates a new ExportRequest instance. */
    constructor($$source: Partial<ExportRequest> = {}) {
        if (!("ids" in $$source)) {
            this["ids"] = [];
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("file_type" in $$source)) {
            this["file_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportRequest {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ids" in $$parsedSource) {
            $$parsedSource["ids"] = $$createField0_0($$parsedSource["ids"]);
        }
        return new ExportRequest($$parsedSource as Partial<ExportRequest>);
    }
}

/**
 * ExportResponse 导出响应
 */
export class ExportResponse {
    /**
     * Success 是否成功
     */
    "success": boolean;

    /**
     * Filename 文件名
     */
    "filename": string;

    /**
     * Data 文件内容（Base64 编码）
     */
    "data": string;

    /**
     * Message 消息
     */
    "message": string;

    /** Creates a new ExportResponse instance. */
    constructor($$source: Partial<ExportResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResponse($$parsedSource as Partial<ExportResponse>);
    }
}

/**
 * GenerateConfigRequest 生成配置请求
 */
export class GenerateConfigRequest {

    /** Creates a new GenerateConfigRequest instance. */
    constructor($$source: Partial<GenerateConfigRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateConfigRequest($$parsedSource as Partial<GenerateConfigRequest>);
    }
}

/**
 * GenerateConfigResponse 生成配置响应
 */
export class GenerateConfigResponse {
    /**
     * Key 加密密钥
     */
    "key": string;

    /**
     * IV 初始化向量
     */
    "iv": string;

    /**
     * Signature 签名密钥
     */
    "signature": string;

    /** Creates a new GenerateConfigResponse instance. */
    constructor($$source: Partial<GenerateConfigResponse> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("iv" in $$source)) {
            this["iv"] = "";
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateConfigResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateConfigResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateConfigResponse($$parsedSource as Partial<GenerateConfigResponse>);
    }
}

/**
 * GenerateRequest Payload 生成请求
 */
export class GenerateRequest {
    /**
     * Type Payload 类型（php/asp/aspx/jsp）
     */
    "type": string;

    /**
     * Function 功能类型（basic/file/command/database/full）
     */
    "function": string;

    /**
     * Password 连接密码
     */
    "password": string;

    /**
     * Encoder 编码器类型
     */
    "encoder": string;

    /**
     * EncryptionKey 加密密钥
     */
    "encryption_key": string;

    /**
     * ObfuscationLevel 混淆级别（none/low/medium/high）
     */
    "obfuscation_level": string;

    /**
     * OutputFilename 输出文件名
     */
    "output_filename": string;

    /**
     * TemplateName 模板名称
     */
    "template_name": string;

    /** Creates a new GenerateRequest instance. */
    constructor($$source: Partial<GenerateRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            this["function"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("encoder" in $$source)) {
            this["encoder"] = "";
        }
        if (!("encryption_key" in $$source)) {
            this["encryption_key"] = "";
        }
        if (!("obfuscation_level" in $$source)) {
            this["obfuscation_level"] = "";
        }
        if (!("output_filename" in $$source)) {
            this["output_filename"] = "";
        }
        if (!("template_name" in $$source)) {
            this["template_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GenerateRequest($$parsedSource as Partial<GenerateRequest>);
    }
}

/**
 * GenerateResponse Payload 生成响应
 */
export class GenerateResponse {
    /**
     * Success 是否成功
     */
    "success": boolean;

    /**
     * Content Payload 内容
     */
    "content": string;

    /**
     * Filename 文件名
     */
    "filename": string;

    /**
     * Size 文件大小
     */
    "size": number;

    /**
     * Message 消息
     */
    "message": string;

    /**
     * Warnings 警告信息
     */
    "warnings"?: string[];

    /** Creates a new GenerateResponse instance. */
    constructor($$source: Partial<GenerateResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GenerateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GenerateResponse {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField5_0($$parsedSource["warnings"]);
        }
        return new GenerateResponse($$parsedSource as Partial<GenerateResponse>);
    }
}

/**
 * GetDatabasesRequest 获取数据库列表请求
 */
export class GetDatabasesRequest {
    "conn_id": number;

    /** Creates a new GetDatabasesRequest instance. */
    constructor($$source: Partial<GetDatabasesRequest> = {}) {
        if (!("conn_id" in $$source)) {
            this["conn_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetDatabasesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetDatabasesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetDatabasesRequest($$parsedSource as Partial<GetDatabasesRequest>);
    }
}

/**
 * GetDatabasesResponse 获取数据库列表响应
 */
export class GetDatabasesResponse {
    "databases": string[];

    /** Creates a new GetDatabasesResponse instance. */
    constructor($$source: Partial<GetDatabasesResponse> = {}) {
        if (!("databases" in $$source)) {
            this["databases"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetDatabasesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetDatabasesResponse {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("databases" in $$parsedSource) {
            $$parsedSource["databases"] = $$createField0_0($$parsedSource["databases"]);
        }
        return new GetDatabasesResponse($$parsedSource as Partial<GetDatabasesResponse>);
    }
}

/**
 * GetImportTemplateRequest 获取导入模板请求
 */
export class GetImportTemplateRequest {
    "format": string;

    /** Creates a new GetImportTemplateRequest instance. */
    constructor($$source: Partial<GetImportTemplateRequest> = {}) {
        if (!("format" in $$source)) {
            this["format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetImportTemplateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetImportTemplateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetImportTemplateRequest($$parsedSource as Partial<GetImportTemplateRequest>);
    }
}

/**
 * GetImportTemplateResponse 获取导入模板响应
 */
export class GetImportTemplateResponse {
    /**
     * Template 模板内容
     */
    "template": string;

    /**
     * Format 格式
     */
    "format": string;

    /** Creates a new GetImportTemplateResponse instance. */
    constructor($$source: Partial<GetImportTemplateResponse> = {}) {
        if (!("template" in $$source)) {
            this["template"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetImportTemplateResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetImportTemplateResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetImportTemplateResponse($$parsedSource as Partial<GetImportTemplateResponse>);
    }
}

/**
 * GetLogsByUserRequest 按用户获取日志请求
 */
export class GetLogsByUserRequest {
    "user": string;
    "limit": number;

    /** Creates a new GetLogsByUserRequest instance. */
    constructor($$source: Partial<GetLogsByUserRequest> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetLogsByUserRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetLogsByUserRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetLogsByUserRequest($$parsedSource as Partial<GetLogsByUserRequest>);
    }
}

/**
 * GetLogsRequest 获取日志请求
 */
export class GetLogsRequest {
    "limit": number;
    "offset": number;

    /** Creates a new GetLogsRequest instance. */
    constructor($$source: Partial<GetLogsRequest> = {}) {
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetLogsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetLogsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetLogsRequest($$parsedSource as Partial<GetLogsRequest>);
    }
}

/**
 * GetLogsResponse 获取日志响应
 */
export class GetLogsResponse {
    "logs": LogEntry[];

    /** Creates a new GetLogsResponse instance. */
    constructor($$source: Partial<GetLogsResponse> = {}) {
        if (!("logs" in $$source)) {
            this["logs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetLogsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetLogsResponse {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField0_0($$parsedSource["logs"]);
        }
        return new GetLogsResponse($$parsedSource as Partial<GetLogsResponse>);
    }
}

/**
 * GetProxyStatusResponse 获取代理状态响应
 */
export class GetProxyStatusResponse {
    /**
     * Enabled 是否启用
     */
    "enabled": boolean;

    /**
     * Type 代理类型
     */
    "type": string;

    /**
     * Host 代理主机
     */
    "host": string;

    /**
     * Port 代理端口
     */
    "port": number;

    /**
     * HasAuth 是否有认证
     */
    "has_auth": boolean;

    /** Creates a new GetProxyStatusResponse instance. */
    constructor($$source: Partial<GetProxyStatusResponse> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("has_auth" in $$source)) {
            this["has_auth"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetProxyStatusResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetProxyStatusResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetProxyStatusResponse($$parsedSource as Partial<GetProxyStatusResponse>);
    }
}

/**
 * GetStatisticsResponse 获取统计响应
 */
export class GetStatisticsResponse {
    "total_logs": number;
    "info_count": number;
    "warning_count": number;
    "error_count": number;
    "critical_count": number;
    "success_count": number;
    "failure_count": number;

    /** Creates a new GetStatisticsResponse instance. */
    constructor($$source: Partial<GetStatisticsResponse> = {}) {
        if (!("total_logs" in $$source)) {
            this["total_logs"] = 0;
        }
        if (!("info_count" in $$source)) {
            this["info_count"] = 0;
        }
        if (!("warning_count" in $$source)) {
            this["warning_count"] = 0;
        }
        if (!("error_count" in $$source)) {
            this["error_count"] = 0;
        }
        if (!("critical_count" in $$source)) {
            this["critical_count"] = 0;
        }
        if (!("success_count" in $$source)) {
            this["success_count"] = 0;
        }
        if (!("failure_count" in $$source)) {
            this["failure_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetStatisticsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetStatisticsResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetStatisticsResponse($$parsedSource as Partial<GetStatisticsResponse>);
    }
}

/**
 * GetTableColumnsRequest 获取表列请求
 */
export class GetTableColumnsRequest {
    "conn_id": number;
    "conn_type": string;
    "table_name": string;

    /** Creates a new GetTableColumnsRequest instance. */
    constructor($$source: Partial<GetTableColumnsRequest> = {}) {
        if (!("conn_id" in $$source)) {
            this["conn_id"] = 0;
        }
        if (!("conn_type" in $$source)) {
            this["conn_type"] = "";
        }
        if (!("table_name" in $$source)) {
            this["table_name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetTableColumnsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetTableColumnsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetTableColumnsRequest($$parsedSource as Partial<GetTableColumnsRequest>);
    }
}

/**
 * GetTableColumnsResponse 获取表列响应
 */
export class GetTableColumnsResponse {
    "columns": entity$0.TableColumn[];

    /** Creates a new GetTableColumnsResponse instance. */
    constructor($$source: Partial<GetTableColumnsResponse> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetTableColumnsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetTableColumnsResponse {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        return new GetTableColumnsResponse($$parsedSource as Partial<GetTableColumnsResponse>);
    }
}

/**
 * GetTablesRequest 获取表请求
 */
export class GetTablesRequest {
    "conn_id": number;
    "conn_type": string;

    /** Creates a new GetTablesRequest instance. */
    constructor($$source: Partial<GetTablesRequest> = {}) {
        if (!("conn_id" in $$source)) {
            this["conn_id"] = 0;
        }
        if (!("conn_type" in $$source)) {
            this["conn_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetTablesRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetTablesRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetTablesRequest($$parsedSource as Partial<GetTablesRequest>);
    }
}

/**
 * GetTablesResponse 获取表响应
 */
export class GetTablesResponse {
    "tables": entity$0.DatabaseTable[];

    /** Creates a new GetTablesResponse instance. */
    constructor($$source: Partial<GetTablesResponse> = {}) {
        if (!("tables" in $$source)) {
            this["tables"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetTablesResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): GetTablesResponse {
        const $$createField0_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField0_0($$parsedSource["tables"]);
        }
        return new GetTablesResponse($$parsedSource as Partial<GetTablesResponse>);
    }
}

/**
 * ImportRequest 导入请求
 */
export class ImportRequest {
    /**
     * Data 导入数据
     */
    "data": string;

    /**
     * Format 导入格式（json/csv/xml）
     */
    "format": string;

    /**
     * FileType 文件类型（webshell/project）
     */
    "file_type": string;

    /** Creates a new ImportRequest instance. */
    constructor($$source: Partial<ImportRequest> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("file_type" in $$source)) {
            this["file_type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportRequest($$parsedSource as Partial<ImportRequest>);
    }
}

/**
 * InstallPluginRequest 安装插件请求
 */
export class InstallPluginRequest {
    "plugin_path": string;

    /** Creates a new InstallPluginRequest instance. */
    constructor($$source: Partial<InstallPluginRequest> = {}) {
        if (!("plugin_path" in $$source)) {
            this["plugin_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallPluginRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallPluginRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InstallPluginRequest($$parsedSource as Partial<InstallPluginRequest>);
    }
}

/**
 * InstallPluginResponse 安装插件响应
 */
export class InstallPluginResponse {
    "success": boolean;
    "message": string;
    "plugin"?: PluginInfoResponse | null;

    /** Creates a new InstallPluginResponse instance. */
    constructor($$source: Partial<InstallPluginResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InstallPluginResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): InstallPluginResponse {
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugin" in $$parsedSource) {
            $$parsedSource["plugin"] = $$createField2_0($$parsedSource["plugin"]);
        }
        return new InstallPluginResponse($$parsedSource as Partial<InstallPluginResponse>);
    }
}

/**
 * LogEntry 日志条目
 */
export class LogEntry {
    "id": number;
    "timestamp": string;
    "level": string;
    "operation": string;
    "user": string;
    "resource": string;
    "action": string;
    "ip_address": string;
    "details": string;
    "success": boolean;
    "duration": number;

    /** Creates a new LogEntry instance. */
    constructor($$source: Partial<LogEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("ip_address" in $$source)) {
            this["ip_address"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): LogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry($$parsedSource as Partial<LogEntry>);
    }
}

/**
 * LogRequest 日志请求
 */
export class LogRequest {
    "level": string;
    "operation": string;
    "user": string;
    "resource": string;
    "action": string;
    "details": string;
    "success": boolean;
    "duration": number;

    /** Creates a new LogRequest instance. */
    constructor($$source: Partial<LogRequest> = {}) {
        if (!("level" in $$source)) {
            this["level"] = "";
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("resource" in $$source)) {
            this["resource"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("details" in $$source)) {
            this["details"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LogRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogRequest($$parsedSource as Partial<LogRequest>);
    }
}

/**
 * OpenWebShellWindowRequest 打开 WebShell 窗口请求
 */
export class OpenWebShellWindowRequest {
    "webshell_id": string;
    "name": string;
    "url": string;

    /** Creates a new OpenWebShellWindowRequest instance. */
    constructor($$source: Partial<OpenWebShellWindowRequest> = {}) {
        if (!("webshell_id" in $$source)) {
            this["webshell_id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenWebShellWindowRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenWebShellWindowRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpenWebShellWindowRequest($$parsedSource as Partial<OpenWebShellWindowRequest>);
    }
}

/**
 * PluginInfoResponse 插件信息响应
 */
export class PluginInfoResponse {
    "id": string;
    "metadata": plugin$0.PluginMetadata | null;
    "status": plugin$0.PluginStatus;
    "is_enabled": boolean;

    /**
     * 是否可以禁用（内置插件通常不可禁用）
     */
    "can_disable": boolean;
    "error"?: string;

    /** Creates a new PluginInfoResponse instance. */
    constructor($$source: Partial<PluginInfoResponse> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = plugin$0.PluginStatus.$zero;
        }
        if (!("is_enabled" in $$source)) {
            this["is_enabled"] = false;
        }
        if (!("can_disable" in $$source)) {
            this["can_disable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginInfoResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginInfoResponse {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField1_0($$parsedSource["metadata"]);
        }
        return new PluginInfoResponse($$parsedSource as Partial<PluginInfoResponse>);
    }
}

/**
 * PluginListResponse 插件列表响应
 */
export class PluginListResponse {
    "total": number;
    "builtin": number;
    "external": number;
    "plugins": (PluginInfoResponse | null)[];

    /** Creates a new PluginListResponse instance. */
    constructor($$source: Partial<PluginListResponse> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("builtin" in $$source)) {
            this["builtin"] = 0;
        }
        if (!("external" in $$source)) {
            this["external"] = 0;
        }
        if (!("plugins" in $$source)) {
            this["plugins"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginListResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginListResponse {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plugins" in $$parsedSource) {
            $$parsedSource["plugins"] = $$createField3_0($$parsedSource["plugins"]);
        }
        return new PluginListResponse($$parsedSource as Partial<PluginListResponse>);
    }
}

/**
 * PluginUpdateInfo 插件更新信息
 */
export class PluginUpdateInfo {
    "has_update": boolean;
    "latest_version"?: string;
    "current_version": string;
    "message": string;
    "download_url"?: string;

    /** Creates a new PluginUpdateInfo instance. */
    constructor($$source: Partial<PluginUpdateInfo> = {}) {
        if (!("has_update" in $$source)) {
            this["has_update"] = false;
        }
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginUpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginUpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginUpdateInfo($$parsedSource as Partial<PluginUpdateInfo>);
    }
}

/**
 * ProxyConfig 代理配置请求
 */
export class ProxyConfig {
    /**
     * Type 代理类型（http/https/socks5）
     */
    "type": string;

    /**
     * Host 代理主机
     */
    "host": string;

    /**
     * Port 代理端口
     */
    "port": number;

    /**
     * Username 用户名（可选）
     */
    "username"?: string;

    /**
     * Password 密码（可选）
     */
    "password"?: string;

    /**
     * Timeout 超时时间（秒）
     */
    "timeout"?: number;

    /** Creates a new ProxyConfig instance. */
    constructor($$source: Partial<ProxyConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig($$parsedSource as Partial<ProxyConfig>);
    }
}

/**
 * ProxyResponse 代理操作响应
 */
export class ProxyResponse {
    /**
     * Success 是否成功
     */
    "success": boolean;

    /**
     * Message 消息
     */
    "message": string;

    /** Creates a new ProxyResponse instance. */
    constructor($$source: Partial<ProxyResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyResponse($$parsedSource as Partial<ProxyResponse>);
    }
}

/**
 * SearchLogsRequest 搜索日志请求
 */
export class SearchLogsRequest {
    "keyword": string;
    "limit": number;

    /** Creates a new SearchLogsRequest instance. */
    constructor($$source: Partial<SearchLogsRequest> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchLogsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchLogsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchLogsRequest($$parsedSource as Partial<SearchLogsRequest>);
    }
}

/**
 * TemplateStats 模板统计
 */
export class TemplateStats {
    /**
     * Total 模板总数
     */
    "total": number;

    /**
     * PHPCount PHP 模板数量
     */
    "php_count": number;

    /**
     * ASPCount ASP 模板数量
     */
    "asp_count": number;

    /**
     * ASPXCount ASPX 模板数量
     */
    "aspx_count": number;

    /**
     * JSPCount JSP 模板数量
     */
    "jsp_count": number;

    /**
     * BuiltinCount 内置模板数量
     */
    "builtin_count": number;

    /**
     * CustomCount 自定义模板数量
     */
    "custom_count": number;

    /** Creates a new TemplateStats instance. */
    constructor($$source: Partial<TemplateStats> = {}) {
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("php_count" in $$source)) {
            this["php_count"] = 0;
        }
        if (!("asp_count" in $$source)) {
            this["asp_count"] = 0;
        }
        if (!("aspx_count" in $$source)) {
            this["aspx_count"] = 0;
        }
        if (!("jsp_count" in $$source)) {
            this["jsp_count"] = 0;
        }
        if (!("builtin_count" in $$source)) {
            this["builtin_count"] = 0;
        }
        if (!("custom_count" in $$source)) {
            this["custom_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TemplateStats instance from a string or object.
     */
    static createFrom($$source: any = {}): TemplateStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TemplateStats($$parsedSource as Partial<TemplateStats>);
    }
}

/**
 * TestConnectionRequest 测试连接请求
 */
export class TestConnectionRequest {
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "database": string;
    "charset": string;
    "ssl_mode": boolean;

    /** Creates a new TestConnectionRequest instance. */
    constructor($$source: Partial<TestConnectionRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("charset" in $$source)) {
            this["charset"] = "";
        }
        if (!("ssl_mode" in $$source)) {
            this["ssl_mode"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestConnectionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TestConnectionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestConnectionRequest($$parsedSource as Partial<TestConnectionRequest>);
    }
}

/**
 * TestConnectionResponse 测试连接响应
 */
export class TestConnectionResponse {
    "success": boolean;
    "message": string;

    /** Creates a new TestConnectionResponse instance. */
    constructor($$source: Partial<TestConnectionResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestConnectionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TestConnectionResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestConnectionResponse($$parsedSource as Partial<TestConnectionResponse>);
    }
}

/**
 * TestEncryptionRequest 测试加密请求
 */
export class TestEncryptionRequest {
    /**
     * Key 加密密钥
     */
    "key": string;

    /**
     * IV 初始化向量
     */
    "iv": string;

    /**
     * Signature 签名密钥
     */
    "signature": string;

    /**
     * TestData 测试数据
     */
    "test_data": string;

    /** Creates a new TestEncryptionRequest instance. */
    constructor($$source: Partial<TestEncryptionRequest> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("iv" in $$source)) {
            this["iv"] = "";
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }
        if (!("test_data" in $$source)) {
            this["test_data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestEncryptionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TestEncryptionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestEncryptionRequest($$parsedSource as Partial<TestEncryptionRequest>);
    }
}

/**
 * TestEncryptionResponse 测试加密响应
 */
export class TestEncryptionResponse {
    /**
     * Success 是否成功
     */
    "success": boolean;

    /**
     * Message 消息
     */
    "message": string;

    /**
     * EncryptedData 加密后的数据
     */
    "encrypted_data": string;

    /**
     * DecryptedData 解密后的数据
     */
    "decrypted_data": string;

    /** Creates a new TestEncryptionResponse instance. */
    constructor($$source: Partial<TestEncryptionResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("encrypted_data" in $$source)) {
            this["encrypted_data"] = "";
        }
        if (!("decrypted_data" in $$source)) {
            this["decrypted_data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestEncryptionResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TestEncryptionResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestEncryptionResponse($$parsedSource as Partial<TestEncryptionResponse>);
    }
}

/**
 * TestProxyRequest 测试代理请求
 */
export class TestProxyRequest {
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "timeout": number;

    /** Creates a new TestProxyRequest instance. */
    constructor($$source: Partial<TestProxyRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TestProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestProxyRequest($$parsedSource as Partial<TestProxyRequest>);
    }
}

/**
 * TestProxyResponse 测试代理响应
 */
export class TestProxyResponse {
    /**
     * Success 是否成功
     */
    "success": boolean;

    /**
     * Message 消息
     */
    "message": string;

    /** Creates a new TestProxyResponse instance. */
    constructor($$source: Partial<TestProxyResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestProxyResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TestProxyResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestProxyResponse($$parsedSource as Partial<TestProxyResponse>);
    }
}

/**
 * UninstallPluginRequest 卸载插件请求
 */
export class UninstallPluginRequest {
    "plugin_id": string;

    /** Creates a new UninstallPluginRequest instance. */
    constructor($$source: Partial<UninstallPluginRequest> = {}) {
        if (!("plugin_id" in $$source)) {
            this["plugin_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UninstallPluginRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): UninstallPluginRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UninstallPluginRequest($$parsedSource as Partial<UninstallPluginRequest>);
    }
}

/**
 * UninstallPluginResponse 卸载插件响应
 */
export class UninstallPluginResponse {
    "success": boolean;
    "message": string;

    /** Creates a new UninstallPluginResponse instance. */
    constructor($$source: Partial<UninstallPluginResponse> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UninstallPluginResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): UninstallPluginResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UninstallPluginResponse($$parsedSource as Partial<UninstallPluginResponse>);
    }
}

/**
 * ValidateConfigRequest 验证配置请求
 */
export class ValidateConfigRequest {
    /**
     * Key 加密密钥
     */
    "key": string;

    /**
     * IV 初始化向量
     */
    "iv": string;

    /**
     * Signature 签名密钥
     */
    "signature": string;

    /** Creates a new ValidateConfigRequest instance. */
    constructor($$source: Partial<ValidateConfigRequest> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("iv" in $$source)) {
            this["iv"] = "";
        }
        if (!("signature" in $$source)) {
            this["signature"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateConfigRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateConfigRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidateConfigRequest($$parsedSource as Partial<ValidateConfigRequest>);
    }
}

/**
 * ValidateConfigResponse 验证配置响应
 */
export class ValidateConfigResponse {
    /**
     * Valid 是否有效
     */
    "valid": boolean;

    /**
     * Errors 错误列表
     */
    "errors": string[];

    /** Creates a new ValidateConfigResponse instance. */
    constructor($$source: Partial<ValidateConfigResponse> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateConfigResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateConfigResponse {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new ValidateConfigResponse($$parsedSource as Partial<ValidateConfigResponse>);
    }
}

/**
 * ValidateImportRequest 验证导入数据请求
 */
export class ValidateImportRequest {
    "data": string;
    "format": string;

    /** Creates a new ValidateImportRequest instance. */
    constructor($$source: Partial<ValidateImportRequest> = {}) {
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateImportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidateImportRequest($$parsedSource as Partial<ValidateImportRequest>);
    }
}

/**
 * ValidateProxyRequest 验证代理配置请求
 */
export class ValidateProxyRequest {
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "password": string;
    "timeout": number;

    /** Creates a new ValidateProxyRequest instance. */
    constructor($$source: Partial<ValidateProxyRequest> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("timeout" in $$source)) {
            this["timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateProxyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateProxyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidateProxyRequest($$parsedSource as Partial<ValidateProxyRequest>);
    }
}

/**
 * ValidateProxyResponse 验证代理配置响应
 */
export class ValidateProxyResponse {
    /**
     * Valid 是否有效
     */
    "valid": boolean;

    /**
     * Errors 错误列表
     */
    "errors": string[];

    /** Creates a new ValidateProxyResponse instance. */
    constructor($$source: Partial<ValidateProxyResponse> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidateProxyResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidateProxyResponse {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField1_0($$parsedSource["errors"]);
        }
        return new ValidateProxyResponse($$parsedSource as Partial<ValidateProxyResponse>);
    }
}

/**
 * ValidationResult 验证结果
 */
export class ValidationResult {
    /**
     * Valid 是否有效
     */
    "valid": boolean;

    /**
     * Warnings 警告信息
     */
    "warnings"?: string[];

    /** Creates a new ValidationResult instance. */
    constructor($$source: Partial<ValidationResult> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField1_0($$parsedSource["warnings"]);
        }
        return new ValidationResult($$parsedSource as Partial<ValidationResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = entity$0.Connection.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = LogEntry.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = entity$0.TableColumn.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = entity$0.DatabaseTable.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = PluginInfoResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = plugin$0.PluginMetadata.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType13);
