// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PayloadHandler Payload 处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../domain/entity/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustomTemplate 添加自定义模板（兼容旧接口）
 * @summary 添加自定义 Payload 模板
 * @param ctx 上下文
 * @param template 模板信息
 * @return 错误信息
 */
export function AddCustomTemplate(template: entity$0.PayloadTemplate | null): $CancellablePromise<void> {
    return $Call.ByID(516952629, template);
}

/**
 * AddTemplate 添加自定义模板
 * @summary 添加自定义 Payload 模板
 * @param ctx 上下文
 * @param req 添加请求
 * @return 错误信息
 */
export function AddTemplate(req: $models.AddCustomTemplateRequest | null): $CancellablePromise<void> {
    return $Call.ByID(1306611910, req);
}

/**
 * DeleteTemplate 删除自定义模板
 * @summary 删除自定义模板
 * @param ctx 上下文
 * @param name 模板名称
 * @return 错误信息
 */
export function DeleteTemplate(name: string): $CancellablePromise<void> {
    return $Call.ByID(793514196, name);
}

/**
 * Generate 生成 Payload
 * @summary 生成 WebShell Payload
 * @param ctx 上下文
 * @param req 生成请求
 * @return 生成结果
 */
export function Generate(req: $models.GenerateRequest | null): $CancellablePromise<$models.GenerateResponse | null> {
    return $Call.ByID(1623499258, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTemplateByName 按名称获取模板
 * @summary 按名称获取模板
 * @param name 模板名称
 * @return 模板信息
 */
export function GetTemplateByName(name: string): $CancellablePromise<entity$0.PayloadTemplate | null> {
    return $Call.ByID(1920966775, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTemplateStats 获取模板统计信息
 * @summary 获取模板统计信息
 * @return 统计信息
 */
export function GetTemplateStats(): $CancellablePromise<$models.TemplateStats | null> {
    return $Call.ByID(150824372).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTemplates 获取所有模板
 * @summary 获取所有可用的 Payload 模板
 * @return 模板列表
 */
export function GetTemplates(): $CancellablePromise<(entity$0.PayloadTemplate | null)[]> {
    return $Call.ByID(1016078186).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Preview 预览 Payload
 * @summary 预览生成的 Payload
 * @param ctx 上下文
 * @param req 生成请求
 * @return Payload 内容
 */
export function Preview(req: $models.GenerateRequest | null): $CancellablePromise<string> {
    return $Call.ByID(3328728463, req);
}

/**
 * RemoveCustomTemplate 移除自定义模板（兼容旧接口）
 * @summary 移除自定义模板
 * @param name 模板名称
 * @return 错误信息
 */
export function RemoveCustomTemplate(name: string): $CancellablePromise<void> {
    return $Call.ByID(3195186224, name);
}

/**
 * ValidatePayload 验证 Payload
 * @summary 验证 Payload 的合法性
 * @param content Payload 内容
 * @param payloadType Payload 类型
 * @return 是否有效和警告信息
 */
export function ValidatePayload(content: string, payloadType: string): $CancellablePromise<$models.ValidationResult | null> {
    return $Call.ByID(4127886579, content, payloadType).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GenerateResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = entity$0.PayloadTemplate.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.TemplateStats.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType3);
const $$createType7 = $models.ValidationResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
