// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PluginHandler 插件管理处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate 检查插件更新
 */
export function CheckUpdate(pluginID: string): $CancellablePromise<$models.PluginUpdateInfo | null> {
    return $Call.ByID(4030300323, pluginID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DisablePlugin 禁用插件
 */
export function DisablePlugin(req: $models.DisablePluginRequest | null): $CancellablePromise<$models.DisablePluginResponse | null> {
    return $Call.ByID(4267842749, req).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * EnablePlugin 启用插件
 */
export function EnablePlugin(req: $models.EnablePluginRequest | null): $CancellablePromise<$models.EnablePluginResponse | null> {
    return $Call.ByID(1235143326, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetPluginDetail 获取插件详情
 */
export function GetPluginDetail(pluginID: string): $CancellablePromise<$models.PluginInfoResponse | null> {
    return $Call.ByID(142677408, pluginID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetPluginList 获取插件列表
 */
export function GetPluginList(): $CancellablePromise<$models.PluginListResponse | null> {
    return $Call.ByID(3800744477).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * InstallPlugin 安装插件
 */
export function InstallPlugin(req: $models.InstallPluginRequest | null): $CancellablePromise<$models.InstallPluginResponse | null> {
    return $Call.ByID(3725343694, req).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * UninstallPlugin 卸载插件
 */
export function UninstallPlugin(req: $models.UninstallPluginRequest | null): $CancellablePromise<$models.UninstallPluginResponse | null> {
    return $Call.ByID(552207967, req).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * UpdatePlugin 更新插件
 */
export function UpdatePlugin(pluginID: string): $CancellablePromise<$models.InstallPluginResponse | null> {
    return $Call.ByID(1508426936, pluginID).then(($result: any) => {
        return $$createType11($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PluginUpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DisablePluginResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.EnablePluginResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.PluginInfoResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.PluginListResponse.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.InstallPluginResponse.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.UninstallPluginResponse.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
