// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectHandler 项目处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../domain/entity/models.js";

/**
 * CreateProject 创建项目
 */
export function CreateProject(name: string, description: string): $CancellablePromise<entity$0.Project | null> {
    return $Call.ByID(3979928215, name, description).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteProject 删除项目
 */
export function DeleteProject(id: string): $CancellablePromise<void> {
    return $Call.ByID(3956231702, id);
}

/**
 * GetDeletedProjects 获取已删除的项目
 */
export function GetDeletedProjects(): $CancellablePromise<entity$0.Project[]> {
    return $Call.ByID(3350231829).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetProjectByID 根据 ID 获取项目
 */
export function GetProjectByID(id: string): $CancellablePromise<entity$0.Project | null> {
    return $Call.ByID(1734442007, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProjects 获取所有项目
 */
export function GetProjects(): $CancellablePromise<entity$0.Project[]> {
    return $Call.ByID(4040895908).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RecoverProject 恢复已删除的项目
 */
export function RecoverProject(id: string): $CancellablePromise<entity$0.Project | null> {
    return $Call.ByID(149237847, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateProject 更新项目
 */
export function UpdateProject(id: string, name: string, description: string, status: number): $CancellablePromise<entity$0.Project | null> {
    return $Call.ByID(2181061144, id, name, description, status).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = entity$0.Project.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
