// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyHandler 代理处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DisableProxy 禁用代理
 */
export function DisableProxy(): $CancellablePromise<$models.ProxyResponse | null> {
    return $Call.ByID(1077195859).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetProxyStatus 获取代理状态
 */
export function GetProxyStatus(): $CancellablePromise<$models.GetProxyStatusResponse | null> {
    return $Call.ByID(1345265357).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SetProxy 设置代理
 */
export function SetProxy(config: $models.ProxyConfig | null): $CancellablePromise<$models.ProxyResponse | null> {
    return $Call.ByID(646094031, config).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * TestProxy 测试代理连接
 */
export function TestProxy(req: $models.TestProxyRequest | null): $CancellablePromise<$models.TestProxyResponse | null> {
    return $Call.ByID(2873026889, req).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ValidateProxy 验证代理配置
 */
export function ValidateProxy(req: $models.ValidateProxyRequest | null): $CancellablePromise<$models.ValidateProxyResponse | null> {
    return $Call.ByID(2985660603, req).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ProxyResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.GetProxyStatusResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.TestProxyResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.ValidateProxyResponse.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
