// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingHandler 设置处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../domain/entity/models.js";

/**
 * GetAllSettings 获取所有设置
 */
export function GetAllSettings(): $CancellablePromise<entity$0.Setting[]> {
    return $Call.ByID(1055587117).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetBoolValue 获取布尔类型设置值
 */
export function GetBoolValue(key: string): $CancellablePromise<boolean> {
    return $Call.ByID(3347581878, key);
}

/**
 * GetIntValue 获取整数类型设置值
 */
export function GetIntValue(key: string): $CancellablePromise<number> {
    return $Call.ByID(2911793267, key);
}

/**
 * GetSettingByKey 根据键名获取设置
 */
export function GetSettingByKey(key: string): $CancellablePromise<entity$0.Setting | null> {
    return $Call.ByID(2843598961, key).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSettingsByCategory 根据分类获取设置
 */
export function GetSettingsByCategory(category: string): $CancellablePromise<entity$0.Setting[]> {
    return $Call.ByID(2982273805, category).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetStringValue 获取字符串类型设置值
 */
export function GetStringValue(key: string): $CancellablePromise<string> {
    return $Call.ByID(4119606701, key);
}

/**
 * UpdateSetting 更新设置值
 */
export function UpdateSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2486879498, key, value);
}

/**
 * UpdateSettings 批量更新设置
 */
export function UpdateSettings(updates: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(3515145595, updates);
}

// Private type creation functions
const $$createType0 = entity$0.Setting.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Nullable($$createType0);
