// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemHandler 系统处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetSystemStatus 获取系统状态
 */
export function GetSystemStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(629513575).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
