// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebShellHandler WebShell 处理器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../domain/entity/models.js";

/**
 * CreateWebShell 创建 WebShell
 */
export function CreateWebShell(projectID: string, url: string, payload: string, cryption: string, encoding: string, proxyType: string, remark: string, status: string): $CancellablePromise<entity$0.WebShell | null> {
    return $Call.ByID(1926760953, projectID, url, payload, cryption, encoding, proxyType, remark, status).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteWebShell 删除 WebShell
 */
export function DeleteWebShell(id: string): $CancellablePromise<void> {
    return $Call.ByID(4279681322, id);
}

/**
 * GetDeletedWebShells 获取已删除的 WebShell（回收站）
 */
export function GetDeletedWebShells(projectID: string): $CancellablePromise<entity$0.WebShell[]> {
    return $Call.ByID(2620972821, projectID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetWebShellByID 根据 ID 获取 WebShell
 */
export function GetWebShellByID(id: string): $CancellablePromise<entity$0.WebShell | null> {
    return $Call.ByID(3019663503, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetWebShells 获取 WebShell 列表
 */
export function GetWebShells(projectID: string, page: number, pageSize: number, searchQuery: string, sortField: string, sortDir: string): $CancellablePromise<[entity$0.WebShell[], number]> {
    return $Call.ByID(3596027052, projectID, page, pageSize, searchQuery, sortField, sortDir).then(($result: any) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    });
}

/**
 * RecoverWebShell 恢复已删除的 WebShell
 */
export function RecoverWebShell(id: string): $CancellablePromise<void> {
    return $Call.ByID(3689986091, id);
}

/**
 * UpdateWebShell 更新 WebShell
 */
export function UpdateWebShell(id: string, projectID: string, url: string, payload: string, cryption: string, encoding: string, proxyType: string, remark: string, status: string): $CancellablePromise<entity$0.WebShell | null> {
    return $Call.ByID(3681368752, id, projectID, url, payload, cryption, encoding, proxyType, remark, status).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = entity$0.WebShell.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
