// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    "name": string;
    "path": string;
    "size": number;
    "is_dir": boolean;
    "mod_time": time$0.Time;
    "permissions"?: string;
    "owner"?: string;

    /** Creates a new FileInfo instance. */
    constructor($$source: Partial<FileInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }
        if (!("mod_time" in $$source)) {
            this["mod_time"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FileInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo($$parsedSource as Partial<FileInfo>);
    }
}

/**
 * FileListResponse 文件列表响应
 */
export class FileListResponse {
    "path": string;
    "files": FileInfo[];
    "error"?: string;

    /** Creates a new FileListResponse instance. */
    constructor($$source: Partial<FileListResponse> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileListResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): FileListResponse {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new FileListResponse($$parsedSource as Partial<FileListResponse>);
    }
}

// Private type creation functions
const $$createType0 = FileInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
