// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Permission 权限定义
 */
export enum Permission {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PermissionFileSystem 文件系统访问
     */
    PermissionFileSystem = "fs:readwrite",

    /**
     * PermissionNetwork 网络访问
     */
    PermissionNetwork = "network",

    /**
     * PermissionDatabase 数据库访问
     */
    PermissionDatabase = "database",

    /**
     * PermissionExecute 命令执行
     */
    PermissionExecute = "execute",

    /**
     * PermissionClipboard 剪贴板访问
     */
    PermissionClipboard = "clipboard",

    /**
     * PermissionSettings 设置访问
     */
    PermissionSettings = "settings",

    /**
     * PermissionPlugin 插件管理
     */
    PermissionPlugin = "plugin",
};

/**
 * PluginDependency 插件依赖
 */
export class PluginDependency {
    /**
     * ID 依赖插件 ID
     */
    "id": string;

    /**
     * Version 版本约束 (如："^1.0.0", ">=2.0.0", "~1.2.0")
     */
    "version": string;

    /**
     * Required 是否必需
     */
    "required": boolean;

    /** Creates a new PluginDependency instance. */
    constructor($$source: Partial<PluginDependency> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("required" in $$source)) {
            this["required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginDependency instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginDependency {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginDependency($$parsedSource as Partial<PluginDependency>);
    }
}

/**
 * PluginMetadata 插件元数据
 */
export class PluginMetadata {
    /**
     * ID 插件唯一标识
     */
    "id": string;

    /**
     * Name 插件名称
     */
    "name": string;

    /**
     * Version 版本号 (语义化版本：MAJOR.MINOR.PATCH)
     */
    "version": string;

    /**
     * Description 插件描述
     */
    "description": string;

    /**
     * Author 作者信息
     */
    "author": string;

    /**
     * Type 插件类型
     */
    "type": PluginType;

    /**
     * Category 插件分类
     */
    "category": string;

    /**
     * Tags 标签
     */
    "tags"?: string[];

    /**
     * Homepage 主页 URL
     */
    "homepage"?: string;

    /**
     * Repository 代码仓库 URL
     */
    "repository"?: string;

    /**
     * License 许可证
     */
    "license"?: string;

    /**
     * MinAppVersion 最低应用版本要求
     */
    "min_app_version"?: string;

    /**
     * Dependencies 依赖插件列表
     */
    "dependencies"?: PluginDependency[];

    /**
     * Permissions 权限声明
     */
    "permissions"?: Permission[];

    /**
     * CreatedAt 创建时间
     */
    "created_at"?: time$0.Time;

    /**
     * UpdatedAt 更新时间
     */
    "updated_at"?: time$0.Time;

    /** Creates a new PluginMetadata instance. */
    constructor($$source: Partial<PluginMetadata> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("author" in $$source)) {
            this["author"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = PluginType.$zero;
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginMetadata {
        const $$createField7_0 = $$createType0;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        if ("dependencies" in $$parsedSource) {
            $$parsedSource["dependencies"] = $$createField12_0($$parsedSource["dependencies"]);
        }
        if ("permissions" in $$parsedSource) {
            $$parsedSource["permissions"] = $$createField13_0($$parsedSource["permissions"]);
        }
        return new PluginMetadata($$parsedSource as Partial<PluginMetadata>);
    }
}

/**
 * PluginStatus 插件状态
 */
export enum PluginStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PluginStatusLoaded 已加载
     */
    PluginStatusLoaded = "loaded",

    /**
     * PluginStatusUnloaded 未加载
     */
    PluginStatusUnloaded = "unloaded",

    /**
     * PluginStatusEnabled 已启用
     */
    PluginStatusEnabled = "enabled",

    /**
     * PluginStatusDisabled 已禁用
     */
    PluginStatusDisabled = "disabled",

    /**
     * PluginStatusError 错误状态
     */
    PluginStatusError = "error",
};

/**
 * PluginType 插件类型
 */
export enum PluginType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * PluginTypeBuiltin 内置插件
     */
    PluginTypeBuiltin = "builtin",

    /**
     * PluginTypeExternal 外置插件
     */
    PluginTypeExternal = "external",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = PluginDependency.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
