// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gorm$0 from "../../../../gorm.io/gorm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

/**
 * Project 项目实体
 */
export class Project {
    "id": string;
    "name": string;
    "description": string;

    /**
     * 0=Active, 1=Archived
     */
    "status": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * 软删除标记
     */
    "deletedAt": gorm$0.DeletedAt;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("deletedAt" in $$source)) {
            this["deletedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * Setting 设置实体 - 用于存储应用程序的所有设置项
 */
export class Setting {
    /**
     * 自增 ID
     */
    "id": number;

    /**
     * 设置键名（如：theme, language）
     */
    "key": string;

    /**
     * 设置值（统一存储为字符串）
     */
    "value": string;

    /**
     * 数据类型：string, int, bool, json, color
     */
    "type": string;

    /**
     * 分类：appearance, network, proxy, general
     */
    "category": string;

    /**
     * 显示名称
     */
    "name": string;

    /**
     * 描述
     */
    "description": string;

    /**
     * 更新时间
     */
    "updatedAt": time$0.Time;

    /**
     * 创建时间
     */
    "createdAt": time$0.Time;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}

/**
 * WebShell WebShell 实体
 */
export class WebShell {
    "id": string;
    "projectId": string;
    "url": string;
    "payload": string;
    "cryption": string;
    "encoding": string;
    "proxyType": string;
    "remark": string;
    "status": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WebShell instance. */
    constructor($$source: Partial<WebShell> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("cryption" in $$source)) {
            this["cryption"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("proxyType" in $$source)) {
            this["proxyType"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebShell instance from a string or object.
     */
    static createFrom($$source: any = {}): WebShell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebShell($$parsedSource as Partial<WebShell>);
    }
}
