// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App 应用结构体
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";

/**
 * CreateWebShell 创建 WebShell
 */
export function CreateWebShell(shell: models$0.WebShell): $CancellablePromise<void> {
    return $Call.ByID(1100281053, shell);
}

/**
 * DeleteProject 删除项目
 */
export function DeleteProject(projectName: string): $CancellablePromise<void> {
    return $Call.ByID(3379369923, projectName);
}

/**
 * DeleteWebShell 删除 WebShell
 */
export function DeleteWebShell(id: string): $CancellablePromise<void> {
    return $Call.ByID(66317606, id);
}

/**
 * GetWebShells 获取 WebShell 列表
 */
export function GetWebShells(projectName: string, page: number, pageSize: number, searchQuery: string, sortField: string, sortDir: string): $CancellablePromise<[models$0.WebShell[], number]> {
    return $Call.ByID(95418832, projectName, page, pageSize, searchQuery, sortField, sortDir).then(($result: any) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    });
}

/**
 * UpdateWebShell 更新 WebShell
 */
export function UpdateWebShell(shell: models$0.WebShell): $CancellablePromise<void> {
    return $Call.ByID(4054717868, shell);
}

// Private type creation functions
const $$createType0 = models$0.WebShell.createFrom;
const $$createType1 = $Create.Array($$createType0);
