// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SystemStatus 系统状态结构体
 */
export class SystemStatus {
    "memoryUsage": string;
    "processId": string;
    "cpuUsage": string;
    "uptime": string;

    /** Creates a new SystemStatus instance. */
    constructor($$source: Partial<SystemStatus> = {}) {
        if (!("memoryUsage" in $$source)) {
            this["memoryUsage"] = "";
        }
        if (!("processId" in $$source)) {
            this["processId"] = "";
        }
        if (!("cpuUsage" in $$source)) {
            this["cpuUsage"] = "";
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStatus($$parsedSource as Partial<SystemStatus>);
    }
}

/**
 * WindowCreateEvent is the event data for creating a new window
 */
export class WindowCreateEvent {
    "title": string;
    "width": number;
    "height": number;
    "x": number;
    "y": number;

    /** Creates a new WindowCreateEvent instance. */
    constructor($$source: Partial<WindowCreateEvent> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowCreateEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowCreateEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowCreateEvent($$parsedSource as Partial<WindowCreateEvent>);
    }
}
