// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WebShell WebShell 模型
 */
export class WebShell {
    "id": string;
    "projectId": string;
    "name": string;
    "url": string;
    "payload": string;
    "cryption": string;
    "encoding": string;
    "proxyType": string;
    "remark": string;
    "createTime": string;
    "updateTime": string;
    "status": string;

    /** Creates a new WebShell instance. */
    constructor($$source: Partial<WebShell> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("cryption" in $$source)) {
            this["cryption"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("proxyType" in $$source)) {
            this["proxyType"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = "";
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebShell instance from a string or object.
     */
    static createFrom($$source: any = {}): WebShell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebShell($$parsedSource as Partial<WebShell>);
    }
}
