// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Project 项目模型
 */
export class Project {
    "id": string;
    "name": string;
    "description": string;

    /**
     * 0=Active, 1=Archived
     */
    "status": number;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * WebShell WebShell 模型
 */
export class WebShell {
    "id": string;
    "projectId": string;
    "url": string;
    "payload": string;
    "cryption": string;
    "encoding": string;
    "proxyType": string;
    "remark": string;
    "status": string;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /** Creates a new WebShell instance. */
    constructor($$source: Partial<WebShell> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = "";
        }
        if (!("cryption" in $$source)) {
            this["cryption"] = "";
        }
        if (!("encoding" in $$source)) {
            this["encoding"] = "";
        }
        if (!("proxyType" in $$source)) {
            this["proxyType"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebShell instance from a string or object.
     */
    static createFrom($$source: any = {}): WebShell {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebShell($$parsedSource as Partial<WebShell>);
    }
}
