// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listWebshells: (projectId: string | null) => typedError<Webshell[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("list_webshells", { projectId })),
	getWebshell: (id: string) => typedError<Webshell, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("get_webshell", { id })),
	createWebshell: (input: CreateWebshellInput) => typedError<Webshell, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("create_webshell", { input })),
	updateWebshell: (id: string, input: UpdateWebshellInput) => typedError<Webshell, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("update_webshell", { id, input })),
	deleteWebshell: (id: string) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("delete_webshell", { id })),
	testConnection: (id: string) => typedError<ConnectionResult, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("test_connection", { id })),
	resetRedeployStatus: (id: string) => typedError<Webshell, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("reset_redeploy_status", { id })),
	listProjects: () => typedError<Project[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("list_projects")),
	createProject: (input: CreateProjectInput) => typedError<Project, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("create_project", { input })),
	updateProject: (id: string, input: UpdateProjectInput) => typedError<Project, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("update_project", { id, input })),
	deleteProject: (id: string) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("delete_project", { id })),
	listPayloads: () => typedError<Payload[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("list_payloads")),
	createPayload: (input: CreatePayloadInput) => typedError<Payload, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("create_payload", { input })),
	generatePayload: (payloadId: string | null, webshellId: string | null, config: PayloadConfig) => typedError<string, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("generate_payload", { payloadId, webshellId, config })),
	listPayloadHistory: (payloadId: string) => typedError<PayloadHistoryEntry[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("list_payload_history", { payloadId })),
	openConsole: (webshellId: string) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("open_console", { webshellId })),
	execCommand: (webshellId: string, cmd: string) => typedError<string, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("exec_command", { webshellId, cmd })),
	listFiles: (webshellId: string, path: string) => typedError<"Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never }, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("list_files", { webshellId, path })),
	downloadFile: (webshellId: string, path: string, transferId: string) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("download_file", { webshellId, path, transferId })),
	uploadFile: (webshellId: string, path: string, data: number[]) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("upload_file", { webshellId, path, data })),
	connectDatabase: (webshellId: string, dbType: string, connStr: string) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("connect_database", { webshellId, dbType, connStr })),
	executeQuery: (webshellId: string, query: string) => typedError<"Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never }, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("execute_query", { webshellId, query })),
	listPlugins: () => typedError<Plugin[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("list_plugins")),
	enablePlugin: (id: string) => typedError<Plugin, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("enable_plugin", { id })),
	disablePlugin: (id: string) => typedError<Plugin, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("disable_plugin", { id })),
	getSettings: () => typedError<Config, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("get_settings")),
	updateSettings: (input: UpdateSettingsInput) => typedError<Config, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("update_settings", { input })),
	unlock: (password: string) => typedError<boolean, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("unlock", { password })),
	setMasterPassword: (oldPassword: string | null, newPassword: string) => typedError<null, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("set_master_password", { oldPassword, newPassword })),
	getAppInfo: () => typedError<AppInfo, {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("get_app_info")),
	getAuditLog: (limit: number | null) => typedError<AuditEntry[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("get_audit_log", { limit })),
	testConnections: (ids: string[]) => typedError<BatchTestResult[], {
	kind: string,
	message: string,
}>(__TAURI_INVOKE("test_connections", { ids })),
};

/* Types */
export type AppInfo = {
	version: string,
	dataDir: string,
	dbPath: string,
	logsDir: string,
};

export type AppearanceConfig = {
	theme: string,
	language: string,
	accent_color: string,
};

export type AuditEntry = {
	id: string,
	webshellId: string | null,
	action: string,
	detail: string,
	createdAt: number,
};

export type BatchTestResult = {
	id: string,
	result: ConnectionResult,
};

export type CodecStep = { type: "base64" } | { type: "aes256_gcm" } | { type: "xor_key"; key: string } | { type: "url_encode" } | { type: "gzip_compress" } | { type: "hex_encode" };

export type Config = {
	meta: MetaConfig,
	appearance: AppearanceConfig,
	window: WindowConfig,
	connection: ConnectionConfig,
	security: SecurityConfig,
	logging: LoggingConfig,
};

export type ConnectionConfig = {
	timeout_secs: number,
	retry_count: number,
	proxy_enabled: boolean,
	proxy_type: string,
	proxy_host: string,
	proxy_port: number,
};

export type ConnectionResult = {
	success: boolean,
	latencyMs: number | null,
	error: string | null,
	fingerprint: WebshellFingerprint | null,
};

export type CreatePayloadInput = {
	name: string,
	config: PayloadConfig,
};

export type CreateProjectInput = {
	name: string,
	description: string | null,
};

export type CreateWebshellInput = {
	name: string,
	url: string,
	password: string,
	payloadType: PayloadType,
	projectId: string | null,
	tags?: string[],
	customHeaders?: { [key in string]: string },
	cookies?: { [key in string]: string },
	proxyOverride: string | null,
	httpMethod?: string,
	c2Profile?: string,
	cryptoChain?: CryptoChain,
	notes: string | null,
};

export type CryptoChain = {
	steps: CodecStep[],
};

export type LoggingConfig = {
	level: string,
	max_file_size_mb: number,
	max_files: number,
};

export type MetaConfig = {
	config_version: number,
};

export type ObfuscateConfig = {
	level: number,
	seed: number | null,
	targetVersion: string | null,
};

export type Payload = {
	id: string,
	name: string,
	payloadType: PayloadType,
	config: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never },
	createdAt: number,
};

export type PayloadConfig = {
	payloadType: PayloadType,
	password: string,
	cryptoChain: CryptoChain,
	c2Profile: string,
	obfuscate: ObfuscateConfig,
	targetVersion: string | null,
};

export type PayloadHistoryEntry = {
	id: string,
	payloadId: string | null,
	webshellId: string | null,
	code: string,
	templateVersion: string,
	createdAt: number,
};

export type PayloadType = "php" | "jsp" | "asp" | "aspx";

export type Plugin = {
	id: string,
	name: string,
	version: string,
	enabled: boolean,
	config: "Null" | ({ Bool: boolean }) & { Array?: never; Number?: never; Object?: never; String?: never } | ({ Number: ({ f64: number }) & { i64?: never; u64?: never } | ({ i64: number }) & { f64?: never; u64?: never } | ({ u64: number }) & { f64?: never; i64?: never } }) & { Array?: never; Bool?: never; Object?: never; String?: never } | ({ String: string }) & { Array?: never; Bool?: never; Number?: never; Object?: never } | ({ Array: Value[] }) & { Bool?: never; Number?: never; Object?: never; String?: never } | ({ Object: { [key in string]: Value } }) & { Array?: never; Bool?: never; Number?: never; String?: never },
	source: string,
	createdAt: number,
	updatedAt: number,
};

export type Project = {
	id: string,
	name: string,
	description: string | null,
	createdAt: number,
	updatedAt: number,
};

export type SecurityConfig = {
	encryption: string,
	key_rotation_days: number,
	salt: string,
	master_password_enabled: boolean,
	master_password_hash: string,
	idle_lock_minutes: number,
};

export type UpdateProjectInput = {
	name: string | null,
	description: string | null,
};

export type UpdateSettingsInput = {
	theme: string | null,
	language: string | null,
	accentColor: string | null,
};

export type UpdateWebshellInput = {
	name: string | null,
	url: string | null,
	password: string | null,
	projectId: string | null,
	tags: string[] | null,
	customHeaders: { [key in string]: string } | null,
	cookies: { [key in string]: string } | null,
	proxyOverride: string | null,
	httpMethod: string | null,
	c2Profile: string | null,
	cryptoChain: CryptoChain | null,
	notes: string | null,
	status: string | null,
};

export type Webshell = {
	id: string,
	name: string,
	url: string,
	password: string,
	payloadType: PayloadType,
	projectId: string | null,
	status: string,
	tags: string[],
	customHeaders: { [key in string]: string },
	cookies: { [key in string]: string },
	proxyOverride: string | null,
	httpMethod: string,
	c2Profile: string,
	cryptoChain: CryptoChain,
	fingerprint: WebshellFingerprint | null,
	notes: string | null,
	lastConnectedAt: number | null,
	createdAt: number,
	updatedAt: number,
};

export type WebshellFingerprint = {
	os: string | null,
	runtime: string | null,
	runtimeVer: string | null,
	username: string | null,
	cwd: string | null,
	disabledFns: string[],
	writable: boolean | null,
	lastProbedAt: number | null,
};

export type WindowConfig = {
	x: number,
	y: number,
	width: number,
	height: number,
	maximized: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

